spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/one-citations
logging:
  level:
    org:
      springframework:
        security: debug
